---
# Ansible Inventory File
#
# This inventory file contains the configuration parameters and variables
# used in the Ansible playbook for deploying and managing infrastructure
# and applications.
#
# Contact: Adam Fordyce - <adam.fordyce@capgemini.com>
# Version: 1.0
# Last Updated: 11th June 2023
# Source Control: https://github.com/adamfordyce11/azure-inventories.git
# Documentation: https://github.com/adamfordyce11/azure-inventories
#
# Please review and modify the values below to match your environment.

# Virtual Machine
# The hostname of the virtual machine.
virtual_machine: "{{ inventory_hostname }}"

# Public IP
# The public IP address of the virtual machine.
public_ip: "{{ virtual_machine }}-public-ip"

# Network Interface Card (NIC)
# The network interface card associated with the virtual machine.
nic: "{{ virtual_machine }}-nic"

# RHEL Version
# The version of Red Hat Enterprise Linux (RHEL) used in the group.
group_rhel_version: "8.4"

# Security Group
# The name of the security group associated with the virtual machine.
security_group: "{{ site_resource_group }}-{{ virtual_machine }}-secgroup"

# Security Group Rules
# The rules defining the inbound access to the security group.
security_group_rules:
  - name: SSH
    protocol: Tcp
    destination_port_range: 22
    access: Allow
    priority: 1001
    direction: Inbound

# Virtual Machine Flavor
# The flavor (size) of the virtual machine.
flavor: Standard_D4s_v5

# License Type
# The license type for the RHEL virtual machine.
license_type: "RHEL_BYOS"

# Plan
# The plan details for the RHEL virtual machine.
plan:
  name: "rhel-lvm84-gen2"
  product: "rhel-byos"
  publisher: "redhat"

# Azure Image
# The Azure image details used for provisioning the virtual machine.
azure_image:
  publisher: "redhat"
  offer: "rhel-byos"
  sku: "rhel-lvm84-gen2"
  version: "8.4.20220317"

# Blob Image Source
# The source URL of the blob image.
blob_image_source: "https://{{ site_storage_account }}.blob.core.windows.net/{{ site_storage_container }}/{{ site_image_name_staging }}.{{ site_image_format }}"

# VM Image Source
# The source details for the virtual machine image.
vm_image_source:
  name: "{{ groups['staging'][0] }}"
  resource_group: "{{ site_resource_group }}"
  type: "virtual_machines"

# OS Disk Size
# The size (in GB) of the operating system (OS) disk.
os_disk_size: 100

# Repositories
# The list of repositories for package installation.
# Add or modify the repository names based on your requirements.
repos:
  - "rhel-8-for-x86_64-baseos-e4s-rpms"
  - "rhel-8-for-x86_64-appstream-e4s-rpms"
  - "rhel-8-for-x86_64-sap-solutions-e4s-rpms"
  - "rhel-8-for-x86_64-sap-netweaver-e4s-rpms"
  - "rhel-8-for-x86_64-highavailability-e4s-rpms"

...
